apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stakater-monitoring-role-binding
  labels:
    app: prometheus-operator-operator
    chart: prometheus-operator-5.0.13
    release: "operatic-mouse"
    heritage: "Tiller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stakater-monitoring-cluster-role
subjects:
  - kind: ServiceAccount
    name: stakater-monitoring
    namespace: monitoring
