apiVersion: v1
kind: ServiceAccount
metadata:
  name: stakater-monitoring
  labels:
    app: prometheus-operator-alertmanager
    chart: prometheus-operator-5.0.13
    release: "operatic-mouse"
    heritage: "Tiller"
