.ONESHELL:
SHELL= /bin/bash

CLOUD_PROVIDER ?= aws
ARGS := $(STAKATER_PLATFORM_SSH_GIT_URL) $(STAKATER_PLATFORM_BRANCH) $(DOMAIN) $(BASE64_ENCODED_AWS_ACCESS_KEY_ID) $(BASE64_ENCODED_AWS_SECRET_ACCESS_KEY) $(BASE64_ENCODED_IMC_CONFIG) $(BASE64_ENCODED_JENKINS_CFG) $(KEYCLOAK_CLIENT_ID) $(KEYCLOAK_CLIENT_SECRET) $(BASE64_ENCODED_HUB_TOKEN) $(BASE64_ENCODED_GITLAB_TOKEN) $(BASE64_ENCODED_BITBUCKET_TOKEN) $(BASE64_ENCODED_ADMIN_ACCOUNT_JSON) $(BASE64_ENCODED_CLUSTER_ACCOUNT_JSON) $(NEXUS_ADMIN_ACCOUNT_USERNAME) $(NEXUS_CLUSTER_ACCOUNT_USERNAME) $(BASE64_ENCODED_ALERTMANAGER_CONFIG) $(BASE64_ENCODED_KEYCLOAK_CONFIG) $(BASE64_ENCODED_PROXYINJECTOR_CONFIG) $(BASE64_ENCODED_SLACK_CHANNEL) $(BASE64_ENCODED_SLACK_WEBHOOK_URL)

setupvars:
	bash setupvars.sh $(ARGS)
	kubectl apply -f storageclass/$(CLOUD_PROVIDER).yaml

deploy:
	bash install.sh

destroy:
	bash destroy.sh

.PHONY: setupvars deploy destroy