apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticsearchclusters.enterprises.upmc.com
spec:
  group: enterprises.upmc.com
  names:
    kind: ElasticsearchCluster
    listKind: ElasticsearchClusterList
    plural: elasticsearchclusters
    singular: elasticsearchcluster
  scope: Namespaced
  version: v1