apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-docker-cfg
  namespace: delivery
spec:
  encryptedData:
    config.json: AgBbSkm2BqAd1G/yhfNvN3mCJmO949hG9eiJ4NxKLMs/bIZ+hGxxx6QjkRJC9rqu3cAiG/VtO+j+mdj/PcWQ9PYS9aZjfqXiYQXSsNCFhGfmk+JnXBztrEWcLOi/lbSHh7ZbtaIWtZsIVPmDsVUMrqV90fP3tzmk9G9YwaZACXQUxb+LDtDIFRCeBiUv460sUeqBRKGrcTSl4lbx4W1egf0swOFsRgCnu28T+SXp9Emzy6oNoX1aHnjjbRVkLeq4bNp52TSTt0Y487vnARR9h85S92aOx5nnbW+J4FW/jglyBz5OcPrM5haOQCJOXIue1Pf4BqF5RPx632ZHak5mZbotC5nzYO5UPxYPLYgp+vD3k69enD/Nvw7OJUbbGZwC/1A1i0WMKbzNo1K0s2IavEyXwZYxp/UTfDrx/czwi0JEsyeoAiz4Ww8fvx8gRrC+Wqw1dfFcyDZ1tkIZizCKaM/Ov7jB1P9cLUjCjA88BtsD+NfJ3eMQVwQ479+xVYgCCg5HnROxt9dOQYB/Al2ch/q0ZpzlM89yv8ZFgYY+uZtW+XinI+WHPQx1qtjXnD6DbjAOm5BNjK+JzbHUXxtWgaA9Ui8gGHmKIGR9Eb+yO+Rq9pnDw3Bu1djJvE0rcWODg2wfO/i1ftG6VQt6I+C4VVuwyK8Ih4e6ZwPq2SHG0dubF0QtWON1cOtsmkoY+HXuS0k0za6ARxRxtmn7xfUwq+3X9s0Qj9JfO+04ye/XoTuCc4C0psTT6gRqNON3FLM9mYKym4Idek8o33WQWJqaUsn8MkfTButJafj8/B1s2lqiLC8LxZtkF1SmqNzAkBQvuKf5FyHLCHdpJsZhILVWkgnzl7JWj7pq+JmltwzF/yTit7DKLcgJLG8qW9mtZ1yVzNo3cu6t0ndoG98Khb8P54dvIwA+5oHV0SZtwuS+jCWWEb+WURoWiYxuVHzpArk0zqEj9CK+rcPmcIRGISH9P5WsKW+XMGsR
  template:
    metadata:
      name: jenkins-docker-cfg
      namespace: delivery
    type: fabric8.io/jenkins-docker-cfg