apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stakater-control-imc
  namespace: control
spec:
  releaseName: stakater-control-imc
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: ingressmonitorcontroller
    version: 1.0.91
  values:
    ingressMonitorController:
      watchNamespace: "control"
      mount: "secret"
      existingSecret: "imc-config"
      logLevel: info
      logFormat: text
      matchLabels:
        group: com.stakater.platform
        provider: stakater
      deployment:
        labels:
          version: "v1.0.91"
        annotations:
          configmap.reloader.stakater.com/reload: ingressmonitorcontroller
      image:
        name: stakater/ingressmonitorcontroller
        tag: "v1.0.91"
        pullPolicy: IfNotPresent
      configFilePath: /etc/IngressMonitorController/config.yaml