apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: imc-config
  namespace: control
spec:
  encryptedData:
    config.yaml: AgB282B4ImobBMcsGY+QlTex/7DvXwYa23C4dDxY+jNxvvFSS+hOqM+4shm0jPBNAEZ7WOzTXra7lxn+LXzdokWtZVJ0xmbIEaFL3+479TCMyCpUJ8Qe0o/SrAC3Rh0ug9+FFmQ1T4skRT0WGKlRfmpDt6zUYuEwi7CnZ+JXTxLSru9d12ReZhtL7dTnPlQnhuFTnjtQCQBQ7N/LloOJEIFrvMR96KxrkATNyG4B0/HbLeWZWzOCq/XucAUuOrnIfFXumegvm4A/3i50eAXrRddQ5DUkGpW17nSvDLKVoTjEWZH3TJiLZEqEYsL4vS/94AGVC0zLsuh36au/qrKZUKv4QCaTiV51pu8MjAa8lNKSxJVCahD/HqFq6hxxzx/BVoJBrAQPuBaxZJZi5Ml28mlFCdb9hwHD7ucidTd/rrI1Tclzzbaexds1WTaWJeinsWKx8q1tHETLxC2wM1HPGk0RTl4e+Vu5LAQdpk/X39tq2zT8EowqkGWlPxH23ftEH4T6Ba9vgDXbttv6Qe3AX6w0DFb3EDV81euMFEUDecDXSAZuXY43ql6Rwg2xke0wAO2/xu0G40ON4XqCUAVRG984laPg8P479IPoOVFWFNMur0XKzQ+5H0y8/NIVu4SMB/0+fkBmErpxuT83ER+NOUbNshjBpsrjffXcRyixQKpZ59y8mN5rI0ZZLv5yjtEUyEMjiSeb33KvEB1LP/o/Y/4tgn7/qn5fbDRawHFLrIwV+PD71nCWlVq9hgiRVgEj5Ik4IJ+2uAQKDVHDOqjrI6iV/20FhG+TN6Biho5d8YOd3NV1PbUlxGYexcMoe0tl04gstSBbgQ03ZA7gTEbKePZdfRzWlxEOmi27RcU55RtfNIf15FCrTr3s/1VflHgdjZxkMSyjo0hExFTz2XokIFarjlme7fvoLobgwclON0bBvZznjZWvA+tTIRHFQ7IhOrfzJ2LjR84QXVc3EHnxfg4NfMtYnm8BJft/MzdOPNH9O3D5hqj7vneFzgoSxTB/4P18c/d3AiIrl8HaPJvTn7wXCizfMeP3GdrFHxGL8oAICPcGDMMSlouX/j7iCwHG/Hp8g1g1Cd1Dkpf1BsPtSRq/UIiSjh5gPWAw/UEg8CEDeMwYLT0sdtCDiNFgzFelp7CkjL+PWhIAaDsk5Sc7SVjdV8f/QGQFOnJ9AAAyKj2m
  template:
    metadata:
      name: imc-config
      namespace: control