apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stakater-control-descheduler
  namespace: control
spec:
  releaseName: stakater-control-descheduler
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: descheduler
    version: 1.0.10
  values:
    descheduler:    
      namespace: control      
      job:
        schedule: 0 */6 * * *
        parallelism: 1
        completions: 1
        restartPolicy: Never
      config:
        policy: |-
          apiVersion: "descheduler/v1alpha1"
          kind: "DeschedulerPolicy"
          strategies:
            "RemoveDuplicates":
              enabled: true
            "LowNodeUtilization":
              enabled: true
              params:
                nodeResourceUtilizationThresholds:
                  thresholds:
                    "cpu" : 30
                    "memory": 30
                    "pods": 30
                  targetThresholds:
                    "cpu" : 50
                    "memory": 70
                    "pods": 70
