apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stakater-logging-es-client
  namespace: logging
spec:
  releaseName: stakater-logging-es-client
  chart:
    repository: https://helm.elastic.co
    name: elasticsearch
    version:  7.5.0
  values:
    imageTag: 6.8.5
    minimumMasterNodes: 1
    replicas: 1
    esJavaOpts: "-Xmx1g -Xms1g"
    initResources: # they must be in sync with java-options setting above!
      requests:
        memory: 3Gi
        cpu: 500m
      limits:
        memory: 3Gi
        cpu: 1000m
    clusterName: "elasticsearch"
    nodeGroup: "client"
    roles:
      master: "false"
      ingest: "true"
      data: "false"
    persistence:
      enabled: false