#!/bin/bash
source ../variables.config

replace_values() {
  VALUE_TO_REPLACE = ${2}
  if [ -z "$3" ] ; then
    VALUE_TO_REPLACE=`echo -n $2 | base64`
  fi

  echo "Value to replace : $VALUE_TO_REPLACE"

  find ../platform -type f -name "*.yaml" -print0 | xargs -0 sed -i -e "s#${1}#${VALUE_TO_REPLACE}#g"
  find ../config -type f -name "*.*" -print0 | xargs -0 sed -i -e "s#${1}#${VALUE_TO_REPLACE}#g"
}

# Replace following keys with their values in config and platform
replace_values CLOUD_PROVIDER $CLOUD_PROVIDER && \
replace_values DOMAIN $DOMAIN && \
replace_values SSL_CERTIFICATE_CA_CRT $SSL_CERTIFICATE_CA_CRT && \
replace_values SSL_CERTIFICATE_TLS_CRT $SSL_CERTIFICATE_TLS_CRT && \
replace_values SSL_CERTIFICATE_TLS_KEY $SSL_CERTIFICATE_TLS_KEY && \
replace_values STAKATER_PLATFORM_SSH_GIT_URL $STAKATER_PLATFORM_SSH_GIT_URL && \
replace_values STAKATER_PLATFORM_BRANCH $STAKATER_PLATFORM_BRANCH && \
replace_values USER_MAIL $USER_MAIL && \
replace_values USER_NAME $USER_NAME && \
replace_values REPO_ACCESS_TOKEN $REPO_ACCESS_TOKEN && \
replace_values EXTERNAL_DNS_AWS_ACCESS_KEY_ID $EXTERNAL_DNS_AWS_ACCESS_KEY_ID ENCODE && \
replace_values EXTERNAL_DNS_AWS_SECRET_ACCESS_KEY $EXTERNAL_DNS_AWS_SECRET_ACCESS_KEY ENCODE && \
replace_values IMC_API_KEY $IMC_ALERT_CONTACTS && \
replace_values NEXUS_ADMIN_ACCOUNT_USER $NEXUS_ADMIN_ACCOUNT_PASSWORD && \
replace_values NEXUS_CLUSTER_ACCOUNT_USER $NEXUS_CLUSTER_ACCOUNT_PASSWORD && \
replace_values KEYCLOAK_CLIENT_ID $KEYCLOAK_CLIENT_ID && \
replace_values KEYCLOAK_CLIENT_SECRET $KEYCLOAK_CLIENT_SECRET && \
replace_values KEYCLOAK_DEFAULT_PASSWORD $KEYCLOAK_DEFAULT_PASSWORD && \
replace_values KEYCLOAK_DEFAULT_USERNAME $KEYCLOAK_DEFAULT_USERNAME && \
replace_values KEYCLOAK_DB_USER $KEYCLOAK_DB_USER && \
replace_values KEYCLOAK_DB_PASSWORD $KEYCLOAK_DB_PASSWORD && \
replace_values JENKINS_NOTIFICATIONS_SLACK_CHANNEL $JENKINS_NOTIFICATIONS_SLACK_CHANNEL && \
replace_values JENKINS_NOTIFICATIONS_SLACK_WEBHOOK_URL $JENKINS_NOTIFICATIONS_SLACK_WEBHOOK_URL && \
replace_values JENKINS_PIPELINE_GITHUB_TOKEN $JENKINS_PIPELINE_GITHUB_TOKEN && \
replace_values JENKINS_PIPELINE_GITLAB_TOKEN $JENKINS_PIPELINE_GITLAB_TOKEN && \
replace_values JENKINS_PIPELINE_BITBUCKET_TOKEN $JENKINS_PIPELINE_BITBUCKET_TOKEN && \
replace_values JENKINS_DOCKER_RELEASE_USERNAME $JENKINS_DOCKER_RELEASE_USERNAME && \
replace_values JENKINS_DOCKER_RELEASE_PASSWORD $JENKINS_DOCKER_RELEASE_PASSWORD && \
replace_values JENKINS_LOCAL_NEXUS_USERNAME $JENKINS_LOCAL_NEXUS_USERNAME && \
replace_values JENKINS_LOCAL_NEXUS_PASSWORD $JENKINS_LOCAL_NEXUS_PASSWORD && \
replace_values JENKINS_NEXUS_USERNAME $JENKINS_NEXUS_USERNAME && \
replace_values JENKINS_NEXUS_PASSWORD $JENKINS_NEXUS_PASSWORD && \
replace_values SLACK_INFRA_ALERTS_WEBHOOK_URL $SLACK_INFRA_ALERTS_WEBHOOK_URL && \
replace_values SLACK_INFRA_ALERTS_CHANNEL $SLACK_INFRA_ALERTS_CHANNEL && \
replace_values SLACK_APPS_ALERTS_WEBHOOK_URL $SLACK_APPS_ALERTS_WEBHOOK_URL && \
replace_values SLACK_APPS_ALERTS_CHANNEL $SLACK_APPS_ALERTS_CHANNEL && \
replace_values GRAFANA_USERNAME $GRAFANA_USERNAME && \
replace_values GRAFANA_PASSWORD $GRAFANA_PASSWORD

# TODO once values are replaced convert all configs to base64 encoded values

if [ $?==0 ]; then
  exit 0
else
  exit 1
fi