apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: stakater-sc
parameters:
  kind: managed
  storageaccounttype: Standard_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate