apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stakater-logging-es-data
  namespace: logging
spec:
  releaseName: stakater-logging-es-data
  chart:
    repository: https://helm.elastic.co
    name: elasticsearch
    version:  7.5.0
  values:
    imageTag: 6.8.5
    minimumMasterNodes: 1
    replicas: 2
    esJavaOpts: "-Xmx1g -Xms1g"
    initResources: # they must be in synch with java-options setting above!
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 3Gi
        cpu: 2000m
    clusterName: "elasticsearch"
    nodeGroup: "data"
    roles:
      master: "false"
      ingest: "false"
      data: "true"
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: stakater-storageclass
      resources:
        requests:
          storage: 20Gi